version: 2
jobs:
 build:
   docker:
     - image: circleci/node:8-browsers
   steps:
     - checkout
     - restore_cache: # special step to restore the dependency cache
         key: dependency-cache-{{ checksum "package-lock.json" }}
     - run:
         name: Setup Dependencies
         command: npm install
     - run:
         name: Run Server Tests
         command: npm test
     - save_cache: # special step to save the dependency cache
         key: dependency-cache-{{ checksum "package-lock.json" }}
         paths:
           - ./node_modules