version: 2.1
orbs:
    heroku: circleci/heroku@0.0.4
jobs:
    build and test react app:
        docker:
          - image: circleci/node:10-browsers
        steps: 
          - checkout
          - run:
              name: Setup React Dependencies
              command: npm ci --prefix client
          - run:
              name: build react app
              command: npm run build --prefix client
          - run:
              name: Run client Linting
              command: npm run lint --prefix client
          - run:
              name: Run client Tests
              command: npm test --prefix client

    server tests:
        docker:
          - image: circleci/node:10-browsers
        steps:
          - checkout
          - run:
              name: Setup server Dependencies
              command: npm ci --prefix server
          - run:
              name: Lint server
              command: npm run lint --prefix server
          - run:
              name: Test server
              command: npm test --prefix server

    e2e tests:
        docker:
          - image: circleci/node:10-browsers
        steps:
          - checkout
          - run:
              name: Setup e2e Dependencies
              command: npm ci --prefix e2eTests
          - run:
              name: Setup server Dependencies
              command: npm ci --prefix server
          - run:
              name: Setup React Dependencies
              command: npm ci --prefix client
          - run:
              name: build react app
              command: npm run build --prefix client
          - run:
              name: Run e2e Linter
              command: npm run lint --prefix e2eTests
          - run:
              name: Run e2e Tests
              command: npm test --prefix e2eTests

workflows:
    version: 2
    test-deploy:
        jobs:
          - build and test react app
          - server tests:
              requires:
              - build and test react app
          - e2e tests:
              requires:
                - server tests
          - heroku/deploy-via-git:
              requires:
                - server tests
                - e2e tests
              filters:
                branches:
                    only: master

