version: 2.1
orbs:
    heroku: circleci/heroku@0.0.4
jobs:
    test:
        docker:
          - image: circleci/node:10-browsers
        steps:
          - checkout
          - run:
              name: Setup Dependencies
              command: npm ci
          - run:
              name: Run e2e Tests
              command: npm test
          - run:
              name: Setup server Dependencies
              command: npm ci --prefix server
          - run:
              name: Lint server
              command: npm run lint --prefix server
          - run:
              name: Test server
              command: npm test --prefix server
          - run:
              name: Setup client Dependencies
              command: npm ci --prefix client
          - run:
              name: Run client Tests
              command: npm test --prefix client
          - run:
              name: Run client Tests
              command: npm run lint --prefix client

workflows:
    version: 2
    test-deploy:
        jobs:
          - test
          - heroku/deploy-via-git:
              requires:
                - test
              filters:
                branches:
                    only: master

